import { Contact, ContactStatus } from "./types"

export const mockContacts: Contact[] = [
  {
    id: "1",
    prenom: "Marie",
    nom: "Dupont",
    telephone: "+33 6 12 34 56 78",
    email: "marie.dupont@email.com",
    source: "LinkedIn",
    type: "Prospect B2B",
    statut: ContactStatus.Interesse,
    dateRappel: "2026-04-28",
    heureRappel: "14:00",
    notes: "Très intéressée par notre solution. À rappeler lundi.",
  },
  {
    id: "2",
    prenom: "Jean",
    nom: "Martin",
    telephone: "+33 6 23 45 67 89",
    email: "j.martin@company.fr",
    source: "Salon Pro",
    type: "PME",
    statut: ContactStatus.RDV,
    dateRDV: "2026-04-30",
    heureRDV: "10:30",
    notes: "RDV confirmé pour démo produit.",
  },
  {
    id: "3",
    prenom: "Sophie",
    nom: "Bernard",
    telephone: "+33 6 34 56 78 90",
    email: "sophie.b@startup.io",
    source: "Référence client",
    type: "Startup",
    statut: ContactStatus.NonDefini,
    notes: "",
  },
  {
    id: "4",
    prenom: "Pierre",
    nom: "Leroy",
    telephone: "+33 6 45 67 89 01",
    email: "p.leroy@enterprise.com",
    source: "Cold call",
    type: "Grand compte",
    statut: ContactStatus.Rappeler,
    dateRappel: "2026-04-26",
    heureRappel: "09:00",
    notes: "En réunion, demande un rappel demain matin.",
  },
  {
    id: "5",
    prenom: "Isabelle",
    nom: "Moreau",
    telephone: "+33 6 56 78 90 12",
    email: "i.moreau@consulting.fr",
    source: "Site web",
    type: "Consultant",
    statut: ContactStatus.PasInteresse,
    notes: "Déjà équipé chez un concurrent.",
  },
  {
    id: "6",
    prenom: "François",
    nom: "Petit",
    telephone: "+33 6 67 89 01 23",
    email: "francois.petit@agency.com",
    source: "Publicité",
    type: "Agence",
    statut: ContactStatus.Absent,
    notes: "3 tentatives sans réponse.",
  },
  {
    id: "7",
    prenom: "Claire",
    nom: "Rousseau",
    telephone: "+33 6 78 90 12 34",
    email: "c.rousseau@tech.io",
    source: "Webinar",
    type: "Tech",
    statut: ContactStatus.NonDefini,
    notes: "",
  },
  {
    id: "8",
    prenom: "Antoine",
    nom: "Fournier",
    telephone: "+33 6 89 01 23 45",
    email: "a.fournier@retail.fr",
    source: "Partenaire",
    type: "Retail",
    statut: ContactStatus.Injoignable,
    notes: "Numéro incorrect ou changé.",
  },
]

export const tabs = [
  { id: "all", name: "Tous les contacts", color: "#6366f1" },
  { id: "hot", name: "Prospects chauds", color: "#ef4444" },
  { id: "follow", name: "À suivre", color: "#f59e0b" },
]
