name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag Git (v3.0.7, v4.0.0, etc.). Laisser vide pour utiliser la version du package.json"
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  CSC_IDENTITY_AUTO_DISCOVERY: "false" # Empêche electron-builder de chercher un certificat macOS

jobs:
  build-and-publish:
    strategy:
      fail-fast: false  # Ne pas annuler les autres jobs si un échoue
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # récupère aussi les tags pour electron-builder

      - name: Setup Node 20 + cache npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Définir la version de l'application
        id: set_version
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            # Supprimer le préfixe 'v' si présent (ex: v1.0.0 -> 1.0.0)
            INPUT_TAG="${{ github.event.inputs.tag }}"
            VERSION="${INPUT_TAG#v}"
            echo "🏷️ Version spécifiée via input: $VERSION"
            
            # Vérifier la version actuelle
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            echo "📦 Version actuelle: $CURRENT_VERSION"
            
            if [[ "$VERSION" != "$CURRENT_VERSION" ]]; then
              # Mettre à jour le package.json et package-lock.json seulement si différent
              npm version "$VERSION" --no-git-tag-version
              echo "✅ package.json mis à jour de $CURRENT_VERSION vers $VERSION"
            else
              echo "ℹ️ Version identique ($VERSION), pas de mise à jour nécessaire"
            fi
          else
            # Utiliser la version existante si aucun tag n'est fourni
            VERSION=$(node -p "require('./package.json').version")
            echo "📦 Utilisation de la version existante du package.json: $VERSION"
          fi
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Vérifier l'image source pour les icônes
        shell: bash
        run: |
          echo "🔍 Vérification de l'image source..."
          if [[ -f "DDD.png" ]]; then
            echo "✅ Image source DDD.png trouvée"
            ls -la DDD.png
          else
            echo "❌ Erreur: Image source DDD.png manquante"
            exit 1
          fi

      - name: Générer les icônes pour l'application
        continue-on-error: true
        shell: bash
        run: |
          echo "🛠️ Génération des icônes..."
          npm run generate-icons || echo "⚠️ Génération d'icônes échouée, utilisation des icônes existantes"
          echo "✅ Étape de génération terminée"

      - name: Vérifier que les icônes ont été générées
        shell: bash
        run: |
          echo "🔍 Vérification des icônes générées..."
          echo "📁 Contenu du dossier build/:"
          ls -la build/ || true
          
          if [[ -f "build/icon.ico" ]]; then
            echo "✅ Windows icon (icon.ico) trouvé"
            ls -la build/icon.ico
          else
            echo "❌ Erreur: Windows icon (icon.ico) manquant"
            echo "📁 Structure complète du dossier build/:"
            find build/ -type f -name "*.ico" -o -name "*.icns" -o -name "*.png" | head -20 || true
            exit 1
          fi
          
          if [[ -f "build/icon.icns" ]]; then
            echo "✅ macOS icon (icon.icns) trouvé"
            ls -la build/icon.icns
          else
            echo "❌ Erreur: macOS icon (icon.icns) manquant"
            echo "📁 Structure complète du dossier build/:"
            find build/ -type f -name "*.ico" -o -name "*.icns" -o -name "*.png" | head -20 || true
            exit 1
          fi
          
          echo "🎉 Toutes les icônes sont présentes !"

      - name: Vérifier les variables d'environnement Supabase
        shell: bash
        run: |
          echo "🔍 Vérification des secrets Supabase..."
          if [[ "$VITE_SUPABASE_URL" == VITE_SUPABASE_URL* ]]; then
            echo "::warning title=Secret VITE_SUPABASE_URL mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_URL='."
          fi
          if [[ -z "$VITE_SUPABASE_URL" ]]; then
            echo "::warning title=Secret VITE_SUPABASE_URL manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
          fi
          if [[ "$VITE_SUPABASE_ANON_KEY" == VITE_SUPABASE_ANON_KEY* ]]; then
            echo "::warning title=Secret VITE_SUPABASE_ANON_KEY mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_ANON_KEY='."
          fi
          if [[ -z "$VITE_SUPABASE_ANON_KEY" ]]; then
            echo "::warning title=Secret VITE_SUPABASE_ANON_KEY manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
          fi
          echo "ℹ️ Vérification Supabase terminée (les warnings ne bloquent pas le build)"

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Vérifier que le build Vite a réussi
        shell: bash
        run: |
          echo "🔍 Vérification du build Vite..."
          if [[ -f "dist/main/main.js" ]]; then
            echo "✅ Main process construit: dist/main/main.js"
          else
            echo "❌ Main process manquant: dist/main/main.js"
            exit 1
          fi
          if [[ -f "dist/preload/preload.mjs" ]]; then
            echo "✅ Preload script construit: dist/preload/preload.mjs"
          else
            echo "❌ Preload script manquant: dist/preload/preload.mjs"
            exit 1
          fi
          if [[ -f "dist/renderer/index.html" ]]; then
            echo "✅ Renderer construit: dist/renderer/index.html"
          else
            echo "❌ Renderer manquant: dist/renderer/index.html"
            exit 1
          fi
          echo "🎉 Build Vite vérifié avec succès !"

      - name: Build & Publish Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production

      - name: Build & Publish macOS
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production

      - name: Debug - Lister les fichiers générés
        if: always()
        shell: bash
        run: |
          echo "📁 Contenu du dossier release/ :"
          ls -la release/ || echo "❌ Dossier release/ introuvable"
          echo ""
          echo "📁 Contenu du dossier dist/ :"
          ls -la dist/ || echo "❌ Dossier dist/ introuvable"
          echo ""
          echo "📁 Structure complète :"
          find . -name "*.exe" -o -name "*.dmg" -o -name "*.zip" -o -name "*.msi" 2>/dev/null | head -10 || echo "❌ Aucun fichier de distribution trouvé"

      - name: Upload des artefacts Windows
        if: matrix.os == 'windows-latest' && always()
        uses: actions/upload-artifact@v4
        with:
          name: "packages-Windows"
          path: |
            release/*.exe
            release/*.zip
            release/*.msi
          if-no-files-found: warn

      - name: Upload des artefacts macOS
        if: matrix.os == 'macos-latest' && always()
        uses: actions/upload-artifact@v4
        with:
          name: "packages-macOS"
          path: |
            release/*.dmg
            release/*.zip
          if-no-files-found: warn

