name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag Git (v3.0.7, v4.0.0, etc.). Laisser vide pour utiliser la version du package.json"
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  CSC_IDENTITY_AUTO_DISCOVERY: "false" # Empêche electron-builder de chercher un certificat macOS

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # récupère aussi les tags pour electron-builder

      - name: Setup Node 20 + cache npm
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Définir la version à utiliser
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            # Supprimer le préfixe 'v' si présent (v1.0.0 -> 1.0.0)
            VERSION="${{ github.event.inputs.tag }}"
            VERSION="${VERSION#v}"
            
            echo "🏷️  Version spécifiée: $VERSION"
            
            # Mettre à jour le package.json avec la nouvelle version
            npm version $VERSION --no-git-tag-version
            
            echo "✅ Version mise à jour dans package.json"
          else
            CURRENT_VERSION=$(node -p "require('./package.json').version")
            echo "📦 Utilisation de la version du package.json: $CURRENT_VERSION"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Vérifier les variables d'environnement Supabase
        shell: bash
        run: |
          if [[ "$VITE_SUPABASE_URL" == VITE_SUPABASE_URL* ]]; then
            echo "::error title=Secret VITE_SUPABASE_URL mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_URL='."
            exit 1
          fi
          if [[ -z "$VITE_SUPABASE_URL" ]]; then
            echo "::error title=Secret VITE_SUPABASE_URL manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
            exit 1
          fi
          if [[ "$VITE_SUPABASE_ANON_KEY" == VITE_SUPABASE_ANON_KEY* ]]; then
            echo "::error title=Secret VITE_SUPABASE_ANON_KEY mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_ANON_KEY='."
            exit 1
          fi
          if [[ -z "$VITE_SUPABASE_ANON_KEY" ]]; then
            echo "::error title=Secret VITE_SUPABASE_ANON_KEY manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
            exit 1
          fi
          echo "✅ Secrets Supabase semblent corrects."

      - name: Build / Release avec electron-builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: ${{ matrix.os == 'windows-latest' && 'nsis --x64 --publish always' || 'dmg zip --x64 --arm64 --publish always' }}

      - name: Upload des artefacts (facultatif)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ runner.os }}"
          path: |
            release/*.dmg
            release/*.exe
