name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag Git (v3.0.7, v4.0.0, etc.). Laisser vide pour utiliser la version du package.json"
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  CSC_IDENTITY_AUTO_DISCOVERY: "false" # Empêche electron-builder de chercher un certificat macOS

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # récupère aussi les tags pour electron-builder

      - name: Setup Node 20 + cache npm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Définir la version de l'application
        id: set_version
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            # Supprimer le préfixe 'v' si présent (ex: v1.0.0 -> 1.0.0)
            INPUT_TAG="${{ github.event.inputs.tag }}"
            VERSION="${INPUT_TAG#v}"
            echo "🏷️ Version spécifiée via input: $VERSION"
            
            # Mettre à jour le package.json et package-lock.json
            npm version "$VERSION" --no-git-tag-version
            
            echo "✅ package.json mis à jour avec la version $VERSION"
          else
            # Utiliser la version existante si aucun tag n'est fourni
            VERSION=$(node -p "require('./package.json').version")
            echo "📦 Utilisation de la version existante du package.json: $VERSION"
          fi
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Générer les icônes pour l'application
        run: npm run generate-icons

      - name: Vérifier que les icônes ont été générées
        shell: bash
        run: |
          echo "🔍 Vérification des icônes générées..."
          if [[ -f "build/icon.ico" ]]; then
            echo "✅ Windows icon (icon.ico) trouvé"
            ls -la build/icon.ico
          else
            echo "❌ Erreur: Windows icon (icon.ico) manquant"
            exit 1
          fi
          
          if [[ -f "build/icon.icns" ]]; then
            echo "✅ macOS icon (icon.icns) trouvé"
            ls -la build/icon.icns
          else
            echo "❌ Erreur: macOS icon (icon.icns) manquant"
            exit 1
          fi
          
          echo "🎉 Toutes les icônes sont présentes !"

      - name: Vérifier les variables d'environnement Supabase
        shell: bash
        run: |
          if [[ "$VITE_SUPABASE_URL" == VITE_SUPABASE_URL* ]]; then
            echo "::error title=Secret VITE_SUPABASE_URL mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_URL='."
            exit 1
          fi
          if [[ -z "$VITE_SUPABASE_URL" ]]; then
            echo "::error title=Secret VITE_SUPABASE_URL manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
            exit 1
          fi
          if [[ "$VITE_SUPABASE_ANON_KEY" == VITE_SUPABASE_ANON_KEY* ]]; then
            echo "::error title=Secret VITE_SUPABASE_ANON_KEY mal configuré::La valeur du secret ne doit pas commencer par 'VITE_SUPABASE_ANON_KEY='."
            exit 1
          fi
          if [[ -z "$VITE_SUPABASE_ANON_KEY" ]]; then
            echo "::error title=Secret VITE_SUPABASE_ANON_KEY manquant::Le secret est vide ou n'a pas été défini dans les paramètres du dépôt."
            exit 1
          fi
          echo "✅ Secrets Supabase semblent corrects."

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Build & Publish Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production

      - name: Build & Publish macOS
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production

      - name: Upload des artefacts Windows
        if: matrix.os == 'windows-latest' && always()
        uses: actions/upload-artifact@v4
        with:
          name: "packages-Windows"
          path: |
            dist/*.exe
            release/*.exe
          if-no-files-found: warn

      - name: Upload des artefacts macOS
        if: matrix.os == 'macos-latest' && always()
        uses: actions/upload-artifact@v4
        with:
          name: "packages-macOS"
          path: |
            dist/*.dmg
            dist/*.zip
            release/*.dmg
            release/*.zip
          if-no-files-found: warn
